#!/bin/bash



usage()
{
	echo "
	Usage:$0 [URL] [(PostContent).json]
	Example: $0 csye6225-fall2018-chengl.me:8080/csye6225Webapp-1.0-SNAPSHOT/transaction/{id}/attachment receipt.json
  
	"
}


if [ $# -lt 2 ];then
	usage
        exit 1
fi

url=$1




aws s3 cp myS3Bucket/receipt2.jpg s3://csye6225-fall2018-chengl.me.csye6225.com/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers >>/dev/null 



curl -iX POST "$url" -H "Content-Type: application/json" -d @receipt.json 



