#!/bin/bash


usage()
{
	echo "
	Usage:$0 [URL] 
	Example: $0 csye6225-fall2018-chengl.me:8080/csye6225Webapp-1.0-SNAPSHOT/transaction/{id}
	         $0 csye6225-fall2018-chengl.me:8080/csye6225Webapp-1.0-SNAPSHOT/transaction/{id}/attachment/{id}
  
	"
}


if [ $# -lt 1 ];then
	usage
        exit 1
fi

url=$1


curl -iX DELETE "$url" 
