


Resources:
  Csye6225Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "Csye6225Topic"
      Subscription:
      - Endpoint: arn:aws:lambda:us-east-1:398590284929:function:Csye6225LambdaFunction
        Protocol: lambda

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref Csye6225Topic
      FunctionName: arn:aws:lambda:us-east-1:398590284929:function:Csye6225LambdaFunction

