
Resources:
  xingliCsye6225Vpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
  csye6225Subnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId:
        Ref: xingliCsye6225Vpc
  csye6225Subnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId:
        Ref: xingliCsye6225Vpc
  csye6225Subnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: 10.0.3.0/24
      VpcId:
        Ref: xingliCsye6225Vpc
  xingliCsye6225InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
  VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref xingliCsye6225Vpc
      InternetGatewayId: !Ref xingliCsye6225InternetGateway
  xingliCsye6225PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref xingliCsye6225Vpc
  SubnetRouteAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref xingliCsye6225PublicRouteTable
      SubnetId: !Ref csye6225Subnet1
  SubnetRouteAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref xingliCsye6225PublicRouteTable
      SubnetId: !Ref csye6225Subnet2
  SubnetRouteAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId: !Ref xingliCsye6225PublicRouteTable
      SubnetId: !Ref csye6225Subnet3
  AddGatewayRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref xingliCsye6225PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref xingliCsye6225InternetGateway
